routes/front.php
<?php
AdvancedRoute::controller('auth', 'AuthController');
AdvancedRoute::controller('profile', 'ProfileController');
AdvancedRoute::controller('notifications', 'NotificationsController');
AdvancedRoute::controller('roles', 'RolesController');
AdvancedRoute::controller('countries', 'CountriesController');
AdvancedRoute::controller('currencies', 'CurrenciesController');
AdvancedRoute::controller('users', 'UsersController');
AdvancedRoute::controller('posts', 'PostsController');
AdvancedRoute::controller('dashboard', 'DashBoardController');
AdvancedRoute::controller('events', 'EventsController');
AdvancedRoute::controller('groups', 'GroupsController');
AdvancedRoute::controller('programs', 'ProgramsController');
AdvancedRoute::controller('items', 'ItemsController');
AdvancedRoute::controller('contacts', 'ContactsController');
AdvancedRoute::controller('children', 'ChildrenController');
AdvancedRoute::controller('/', 'DashBoardController');

routes/web.php
<?php

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */

/* Route::get('/', function () {
  return view('welcome');
  });
 */
Route::group(['prefix' => (app()->environment() == 'testing') ? 'en' : LaravelLocalization::setLocale(), 'middleware' => ['localeSessionRedirect', 'localizationRedirect', 'localeViewPath']], function() {
    AdvancedRoute::controller('auth', 'AuthController');
    Route::group(['middleware' => ['auth']], function() {
        AdvancedRoute::controller('profile', 'ProfileController');
        AdvancedRoute::controller('notifications', 'NotificationsController');
        Route::group(['prefix' => 'admin'], function() {
            Route::group(['middleware' => ['isAdmin']], function() {
                AdvancedRoute::controller('roles', 'Admin\RolesController');
                AdvancedRoute::controller('users', 'Admin\UsersController');
                AdvancedRoute::controller('posts', 'Admin\PostsController');
                AdvancedRoute::controller('comments', 'Admin\CommentsController');
                AdvancedRoute::controller('faqs', 'Admin\FaqsController');
                AdvancedRoute::controller('contact_messages', 'Admin\ContactMessagesController');
                AdvancedRoute::controller('subscribers', 'Admin\SubscribersController');
                AdvancedRoute::controller('countries', 'Admin\CountriesController');
                AdvancedRoute::controller('tasks', 'Admin\TasksController');
                AdvancedRoute::controller('offers', 'Admin\OffersController');
                AdvancedRoute::controller('questions', 'Admin\QuestionsController');
                AdvancedRoute::controller('rates', 'Admin\RatesController');
                AdvancedRoute::controller('configs', 'Admin\ConfigsController');
                AdvancedRoute::controller('search', 'Admin\SearchController');
                AdvancedRoute::controller('translator', 'Admin\TranslatorController');
                AdvancedRoute::controller('sections', 'Admin\SectionsController');
                AdvancedRoute::controller('transactions', 'Admin\TransactionsController');
                AdvancedRoute::controller('ajax', 'Admin\AjaxController');
                AdvancedRoute::controller('/', 'Admin\DashBoardController');
            });
        });
        AdvancedRoute::controller('comments', 'CommentsController');
        AdvancedRoute::controller('ajax', 'AjaxController');
        AdvancedRoute::controller('/offers', 'OffersController');
        AdvancedRoute::controller('/questions', 'QuestionsController');
    });
    AdvancedRoute::controller('/tasks', 'TasksController');
    AdvancedRoute::controller('/blog', 'BlogController');
    AdvancedRoute::controller('/favourites', 'FavouritesController');
    AdvancedRoute::controller('/bio', 'BioController');
    AdvancedRoute::controller('/posts', 'PostsController');
    AdvancedRoute::controller('/contact_messages', 'ContactMessagesController');
    AdvancedRoute::controller('/subscribers', 'SubscribersController');
    AdvancedRoute::controller('/transactions', 'TransactionsController');
    Route::get('/about', 'PagesController@about');
    Route::get('/terms', 'PagesController@terms');
    Route::get('/privacy', 'PagesController@privacy');
    Route::get('/contact', 'PagesController@contact');
    AdvancedRoute::controller('/', 'HomeController');
});


Route::prefix('api')->group(function () {
    require_once __DIR__ . '/api.php';
});

app/Models/Task.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\SoftDeletes;

class Task extends BaseModel {

    use SoftDeletes,
        \App\Models\Traits\CreatedBy,
        \App\Models\Traits\HasAttach,
        \Laravel\Scout\Searchable;

    ///////////////////////////// has translation
    protected $table = "tasks";
    protected $appends = ['link', 'title_limited', 'content_limited'];
    protected $guarded = [
        'deleted_at',
        'logged_user',
        'image',
        'attachment',
    ];
    protected $hidden = [
        'deleted_at',
    ];
    protected static $attachFields = [
        'image' => [
            'sizes' => ['small' => 'crop,240x180', 'large' => 'resize,720x540'],
            'path' => 'uploads'
        ],
        'attachment' => [
            'path' => 'uploads'
        ],
    ];
    public $rules = [
        'created_by' => 'required',
        'section_id' => 'required',
        'title' => 'required',
        'content' => 'required',
        'where' => 'required',
        'country_id' => "required",
        'location' => 'required',
        'longitude' => 'required',
        'latitude' => 'required',
        'date' => 'required|date|after:today',
        'time' => 'required',
        'budget' => 'required',
        'attachment' => 'nullable|max:8000'
    ];

    public function toSearchableArray() {
        $array = [
            'id' => $this->id,
            'title' => $this->title,
        ];
        return $array;
    }

    public static function boot() {
        parent::boot();
        static::created(function ($row) {
            if (!request()->hasFile('image') && !$row->image) {
                $image = generateImage($row->title, ['small' => '240x180', 'large' => '720x540']);
                $data['image'] = $image;
                \DB::table('tasks')->where('id', $row->id)->update($data);
            }
        });
    }

    public function getSectionsWithParents() {
        return \App\Models\Section::with(['main'])->active()->where('parent_id', '!=', NULL)->get(['id', 'parent_id', 'title'])->groupBy('main.title')
                        ->map(function ($item) {
                            return $item->pluck('title', 'id');
                        });
    }

    public function getCountries() {
        return \App\Models\Country::pluck('title', 'id');
    }

    public function getCreators() {
        return \App\Models\User::where('is_tasker', '=', 1)->pluck('name', 'id');
    }

    public function getWhereValues() {
        $rows = [
            'in_person' => trans('tasks.In person'),
            'remote' => trans('tasks.Remote')
        ];
        return $rows;
    }

    public function getWhereValueAttribute() {
        return $this->getWhereValues()[$this->where];
    }

    public function getTimeValues() {
        $rows = [
            'before_10am' => trans('tasks.Before 10am'),
            '10am_2pm' => trans('tasks.10am to 2pm'),
            'after_2pm_6pm' => trans('tasks.After 2pm to 6pm'),
            'after_6pm' => trans('tasks.After 6pm'),
        ];
        return $rows;
    }

    public function getTimeValueAttribute() {
        return $this->getTimeValues()[$this->time];
    }

    public function getStatusValues() {
        $rows = [
            'draft' => trans('tasks.Draft'),
            'open' => trans('tasks.Open'),
            'assigned' => trans('tasks.Assigned'),
            'done' => trans('tasks.Done'),
            'closed' => trans('tasks.Closed'),
        ];
        return $rows;
    }

    public function getStatusValueAttribute() {
        return $this->getStatusValues()[$this->status];
    }

    public function section() {
        return $this->belongsTo(Section::class, 'section_id')->withTrashed()->withDefault();
    }

    public function creator() {
        return $this->belongsTo(User::class, 'created_by')->withTrashed()->withDefault();
    }

    public function country() {
        return $this->belongsTo(Country::class, 'country_id')->withTrashed()->withDefault();
    }

    public function currency() {
        return $this->belongsTo(Currency::class, 'currency_id')->withTrashed()->withDefault();
    }

    public function offer() {
        return $this->belongsTo(Offer::class, 'offer_id')->withTrashed()->withDefault();
    }

    public function offers() {
        return $this->hasMany(Offer::class)->where('reply_to', NULL);
    }

    public function questions() {
        return $this->hasMany(Question::class);
    }

    public function rates() {
        return $this->morphMany(Rate::class, 'rateable');
    }

    public function scopeOwn($query) {
        return $query->where('created_by', '=', auth()->user()->id);
    }

    public function scopeOpen($query) {
        return $query->where('status', '=', 'open');
    }

    public function scopeClosed($query) {
        return $query->where('status', '=', 'closed');
    }

    public function getData() {
        return $this->with(['creator', 'section', 'country','offers'])
                        ->when(request('status'), function($q) {
                            return $q->where('status', request('status'));
                        })
                        ->when(request('section_id'), function($q) {
                            return $q->where('section_id', request('section_id'));
                        })
                        ->when(request('where'), function($q) {
                            return $q->where('where', request('where'));
                        })
                        ->when(request('time'), function($q) {
                            return $q->where('time', request('time'));
                        })
                        ->when(request('budget'), function($q) {
                            return $q->where('budget', '<=', request('budget'));
                        })
                        ->when(request('country_id'), function($q) {
                            return $q->where('country_id', request('country_id'));
                        })
                        ->when(request('from_date'), function($q) {
                            return $q->where('date', '>=', request('from_date'));
                        })->when(request('to_date'), function($q) {
                            return $q->where('date', '<', date('Y-m-d', strtotime(request('to_date') . ' + 1 day')));
                        })
                        ->when(request('tags'), function($q) {
                            return $q->where('tags', 'LIKE', '%' . request('tags') . '%');
                        })
                        ->when(request('q'), function($q) {
                            return $q->where('title', 'LIKE', '%' . request('q') . '%');
                        });
    }

    public function export($rows, $fileName) {
        return (new \Rap2hpoutre\FastExcel\FastExcel($rows))
                        ->download($fileName . "_" . date("Y-m-d H:i:s") . '.xlsx', function ($row) {
                            $object['id'] = $row->id;
                            $object['Title'] = @$row->title;
                            $object['Section'] = @$row->section->title;
                            $object['Content'] = @$row->content;
                            $object['tags'] = @$row->tags;
                            $object['meta_description'] = @$row->meta_description;
                            $object['meta_keywords'] = @$row->meta_keywords;
                            $object['Created at'] = $row->created_at;
                            $object['Creator'] = $row->creator->name;
                            return $object;
                        });
    }

    public function getLinkAttribute() {
        return app()->make("url")->to('/') . '/' . lang() . '/tasks/details/' . $this->id . '/' . $this->slug;
    }

    public function getTitleLimitedAttribute() {
        return str_limit($this->title, 35);
    }

    public function getContentLimitedAttribute() {
        return str_limit(strip_tags($this->content), 60);
    }

}

app/Http/Controllers/Admin/TasksController.php
<?php

namespace App\Http\Controllers\Admin;

class TasksController extends \App\Http\Controllers\Controller {

    public $model;
    public $module;

    public function __construct(\App\Models\Task $model) {
        $this->module = 'admin/tasks';
        $this->title = trans('app.Tasks');
        $this->model = $model;
        $this->rules = $model->rules;
        $this->offersModule = 'admin/offers';
        $this->questionsModule = 'admin/questions';
    }

    public function getIndex() {
        $data['module'] = $this->module;
        $data['page_title'] = trans('app.List') . " " . $this->title;
        $data['rows'] = $this->model->getData()->latest()->paginate(env('PAGE_LIMIT'));
        $data['row'] = $this->model;
        return view($this->module . '.index', $data);
    }

    public function getCreate() {
        authorize('create-' . $this->module);
        $data['module'] = $this->module;
        $data['page_title'] = trans('app.Create') . " " . $this->title;
        $data['breadcrumb'] = [$this->title => $this->module];
        $data['row'] = $this->model;
        return view($this->module . '.create', $data);
    }

    public function postCreate() {
        authorize('create-' . $this->module);
        $slug= slug(request('title'));
        request()->request->add(['slug' => $slug]);
        $this->validate(request(), $this->rules);
        if ($row = $this->model->create(request()->all())) {
            flash()->success(trans('app.Created successfully'));
            return redirect(lang() . '/' . $this->module);
        }
        flash()->error(trans('app.failed to save'));
    }

    public function getEdit($id) {
        authorize('edit-' . $this->module);
        $data['module'] = $this->module;
        $data['page_title'] = trans('app.Edit') . " " . $this->title;
        $data['breadcrumb'] = [$this->title => $this->module];
        $data['row'] = $this->model->findOrFail($id);
        return view($this->module . '.edit', $data);
    }

    public function postEdit($id) {
        authorize('edit-' . $this->module);
        $slug= slug(request('title'));
        request()->request->add(['slug' => $slug]);
        $row = $this->model->findOrFail($id);
        $this->validate(request(), $this->rules);
        if ($row->update(request()->all())) {
            flash(trans('app.Update successfully'))->success();
            return back();
        }
    }

    public function getView($id) {
        authorize('view-' . $this->module);
        $data['module'] = $this->module;
        $data['page_title'] = trans('app.View') . " " . $this->title;
        $data['breadcrumb'] = [$this->title => $this->module];
        $data['row'] = $this->model->findOrFail($id);
        $data['offersModule'] = $this->offersModule;
        $data['questionsModule'] = $this->questionsModule;
        return view($this->module . '.view', $data);
    }

    public function getDelete($id) {
        authorize('delete-' . $this->module);
        $row = $this->model->findOrFail($id);
        $row->offers()->delete();
        $row->questions()->delete();
        $row->delete();
        flash()->success(trans('app.Deleted Successfully'));
        return back();
    }

    public function getExport() {
        authorize('view-' . $this->module);
        $rows = $this->model->getData()->get();
        if ($rows->isEmpty()) {
            flash()->error(trans('app.There is no results to export'));
            return back();
        }
        return $this->model->export($rows, $this->module);
    }

}

resources/views/front/tasks/__my-tasks.blade.php
@extends('front.layouts.master')

@section('content')
<div class="course-area section-padding course-page">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="section-title-wrapper">
                    <div class="section-title">
                        <h3>{{$page_title}}</h3>
                        <p></p>
                    </div>
                </div>
            </div>
        </div>

        <div>
            @if(auth()->user()->is_tasker)
            <a href="{{lang()}}/tasks/create" class="btn btn-success">
                {{trans('app.Create')}}
            </a> 
            @endif
            {{trans('app.Filter by status')}} : 
            <a href="{{lang()}}/tasks/my-tasks" class="btn btn-secondary">
                {{trans('app.All')}}
            </a> |
            <a href="{{lang()}}/tasks/my-tasks?status=draft" class="btn btn-secondary">
                {{trans('app.Draft')}}
            </a> | 
            <a href="{{lang()}}/tasks/my-tasks?status=open" class="btn btn-secondary">
                {{trans('app.Open')}}
            </a> | 
            <a href="{{lang()}}/tasks/my-tasks?status=assigned" class="btn btn-secondary">
                {{trans('app.Assigned')}}
            </a> |
            <a href="{{lang()}}/tasks/my-tasks?status=closed" class="btn btn-secondary">
                {{trans('app.Closed')}}
            </a>
        </div>
        <div class="row mt-40 mb-40">
            @if (!$rows->isEmpty())
            @foreach ($rows as $row)
            @include('front.app.single')
            @endforeach
            <div class="container">
                <div class="paganition-center center">
                    {!! $rows->appends(['created_by'=>request('created_by'),'section_id'=>request('section_id')])->render() !!}
                </div>
            </div>
            @else
            {{trans("app.There is no results")}}
            @endif
        </div>
    </div>
</div>
@endsection

resources/views/front/tasks/_applied-tasks.blade.php
@extends('front.layouts.master')

@section('content')
<div class="course-area section-padding course-page">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="section-title-wrapper">
                    <div class="section-title">
                        <h3>
                            {{$page_title}}

                        </h3>
                        <p></p>
                    </div>
                </div>
            </div>
        </div>
        @include('front.'.$module.'.partials.filter')
        <div class="row mt-40 mb-40">
            @if (!$rows->isEmpty())
            @foreach ($rows as $row)
            @include('front.tasks.single')
            @endforeach
            <div class="container">
                <div class="paganition-center center">
                    {!! $rows->appends(['section_id'=>request('section_id'),'where'=>request('where'),'country_id'=>request('country_id'),'from_date'=>request('from_date'),'to_date'=>request('to_date'),'time'=>request('time'),'budget'=>request('budget')])->render() !!}
                </div>
            </div>
            @else
            {{trans("app.There is no results")}}
            @endif
        </div>
    </div>
</div>
@endsection

resources/views/front/tasks/create.blade.php
@extends('front.layouts.master')

@section('content')
<div class="course-area section-padding course-page">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="section-title-wrapper">
                    <div class="section-title">
                        <h3>{{$page_title}}</h3>
                        <p></p>
                    </div>
                </div>
            </div>
        </div>
        <div class="section-wrapper">
            <div class="form-layout form-layout-4">
                {!! Form::model($row,['method' => 'post','files' => true] ) !!} 
                {{ csrf_field() }}
                @include('front.tasks.form',$row)
                <!-- custom-file -->
                <div class="form-layout-footer mg-t-30 mg-b-30">
                    <button class="button-default">{{ trans('app.Save') }}</button>
                </div>
                {!! Form::close() !!}
                <br><br>
                <!-- form-layout-footer -->
            </div>
            <!-- form-layout -->
        </div>
    </div>
</div>
@endsection

resources/views/front/tasks/edit.blade.php
@extends('admin.layouts.master')
@section('title')
<h6 class="slim-pagetitle">
    {{ @$page_title }}
</h6>
@endsection
@section('content')
<div class="section-wrapper">
    <div class="form-layout form-layout-4">
        {!! Form::model($row,['method' => 'post','files' => true] ) !!} {{ csrf_field() }}
        @include($module.'.form',$row)
        <!-- custom-file -->
        <div class="form-layout-footer mg-t-30">
            <button class="button-default">{{ trans('app.Save') }}</button>
        </div>
        {!! Form::close() !!}
        <!-- form-layout-footer -->
        <br><br>
    </div>
    <!-- form-layout -->
</div>
@endsection

resources/views/front/tasks/my-tasks.blade.php
@extends('front.layouts.master')

@section('content')
    <div class="course-area section-padding course-page">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="section-title-wrapper">
                        <div class="section-title">
                            <h3>
                                {{$page_title}}
                            </h3>
                            <p></p>
                        </div>
                    </div>
                </div>
                @if(@auth()->user()->is_tasker)
                    <a href="{{lang()}}/tasks/create" class="btn btn-success">
                        {{trans('app.Create task')}}
                    </a>
                @endif
                @include('front.'.$module.'.partials.filter')
                <div class="row">
                    <div class="container mt-40 mb-40">
                        @if (!$rows->isEmpty())
                            <div class="table-responsive">
                                <table class="table display responsive nowrap dataTable">
                                    <thead>
                                    <tr>
                                        <th class="wd-5p">{{trans('tasks.ID')}} </th>
                                        <th class="wd-10p">{{trans('tasks.Section')}} </th>
                                        <th class="wd-10p">{{trans('tasks.Title')}} </th>
                                        <th class="wd-5p">{{trans('tasks.Where')}} </th>
                                        <th class="wd-5p">{{trans('tasks.Date')}} </th>
                                        <th class="wd-5p">{{trans('tasks.Time')}} </th>
                                        <th class="wd-5p">{{trans('tasks.Status')}} </th>
                                        <th class="wd-10p">{{trans('tasks.Created at')}}</th>
                                        <th class="wd-20p">&nbsp;</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach ($rows as $row)
                                        <tr>
                                            <td class="center">{{$row->id}}</td>
                                            <td class="center">{{$row->section->title}}</td>
                                            <td class="center">{{str_limit($row->title,50)}}</td>
                                            <td class="center">{{$row->where_value}}</td>
                                            <td class="center">{{$row->date}}</td>
                                            <td class="center">{{$row->time_value}}</td>
                                            <td class="center">
                                                {{$row->status_value}}
                                                @if($row->status!='closed' && $row->status!='done')
                                                    <a class="btn btn-sm btn-primary" href="{{$module}}/close/{{$row->id}}"
                                                       title="{{trans('posts.Close task')}}">
                                                        {{trans('app.Close')}}
                                                    </a>
                                                @endif


                                            </td>
                                            <td class="center">{{str_limit($row->created_at,10,false)}}</td>
                                            <td class="center">
                                                @if($row->created_by==@auth()->user()->id && ($row->status=='draft' || $row->offers->count()==0))
                                                    <a class="btn btn-sm btn-success" href="{{$module}}/edit/{{$row->id}}"
                                                       title="{{trans('posts.Edit')}}">
                                                        <i class="fa fa-edit"></i>
                                                    </a>
                                                @endif

                                                <a class="btn btn-sm btn-primary" href="{{$module}}/details/{{$row->id}}"
                                                   title="{{trans('tasks.View')}}">
                                                    <i class="fa fa-eye"></i>
                                                </a>
                                                @if($row->created_by==@auth()->user()->id)
                                                    <a class="btn btn-sm btn-danger" href="{{$module}}/delete/{{$row->id}}"
                                                       title="{{trans('tasks.Delete')}}"
                                                       data-confirm="{{trans('tasks.Are you sure you want to delete this item')}}?">
                                                        <i class="fa fa-trash"></i>
                                                    </a>
                                                @endif
                                                @if($row->status=='done')
                                                    <a class="btn btn-sm btn-primary" href="{{$module}}/rate/{{$row->id}}" title="{{trans('tasks.Rate and Review')}}">
                                                        <i class="fa fa-star"></i>
                                                        {{trans('app.Rate')}}
                                                    </a>
                                                @endif
                                            </td>
                                        </tr>
                                    @endforeach
                                    </tbody>
                                </table>
                            </div>
                        @else
                            {{trans("app.There is no results")}}
                        @endif
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/front/tasks/single.blade.php
<div class="col-lg-4 col-md-6 col-12">
    <div class="single-item">
        <div class="single-item-text">
            <h4><a href="{{$row->link}}">{{ucfirst($row->title)}}</a></h4>
            <div class="single-item-text-info">
                <span>{{trans('app.Section')}}: <span>
                        <a href="{{lang()}}/tasks?section_id={{$row->section_id}}">{{$row->section->title}}</a>
                    </span>
                </span>
            </div>
            <div class="single-item-text-info">
                <span>{{trans('app.By')}}: <span>{{$row->creator->name}}</span></span>
                <span>{{trans('app.Status')}}: <span>{{$row->status_value}}</span></span>
                <span>{{trans('app.Views')}}: <span>{{$row->views}}</span></span>
            </div>
            <div class="single-item-text-info">
                <span>{{trans('app.Date')}}: <span>{{$row->date}}, {{@$row->time_value}}</span></span>
            </div>

            <div class="single-item-text-info">
                <span>{{trans('app.Where')}}: <span>{{$row->where_value}}</span></span>
                <span>{{trans('app.Country')}}: <span>{{$row->country->title}}</span></span>
            </div>
            <div class="single-item-text-info">
                <span>{{trans('app.Location')}}: <a href='https://www.google.com/maps/place/{{$row->latitude}},{{@$row->longitude}}' target="_blank" class="text-success">{{$row->location}}</a>
                </span>
            </div>

            <p>{{$row->content_limited}}</p>
            <p class="text-center">
                <span class="btn btn-success">{{$row->budget}} <span class="currency">{{trans('app.EUR')}}</span></span>
            </p>
            @include('front.tasks.partials.counts')
        </div>
        <div class="button-bottom">
            <a href="{{$row->link}}" class="btn btn-theme btn-secondary">{{trans('app.View')}}</a>
<!--            @if($row->created_by==@auth()->user()->id && ($row->status=='draft' || $row->offers->count()==0))
            <a href="{{lang()}}/tasks/edit/{{$row->id}}" class="btn btn-theme btn-success">{{trans('app.Edit')}}</a>
            @endif
            @if($row->created_by==@auth()->user()->id)
            <a href="{{lang()}}/tasks/delete/{{$row->id}}" class="btn btn-theme btn-danger" data-confirm="{{trans('app.Are you sure you want to delete this item')}}?">{{trans('app.Delete')}}</a>
            @endif-->
        </div>
    </div>
</div>